### ISSUE TITLE
/build/{jobid}/artifacts

### ISSUE THREAD

**Issue by cleverca22** [kevinoid/appveyor-swagger#1]
`/build/{jobid}/artifacts` and the relating artifact types are currently missing

**Comment by kevinoid** [comment]
Thanks for the suggestion!  I've added [getBuildArtifacts](https://kevinoid.github.io/appveyor-swagger/redoc/#operation/getBuildArtifacts), [getBuildArtifact](https://kevinoid.github.io/appveyor-swagger/redoc/#operation/getBuildArtifact), and [getProjectArtifact](https://kevinoid.github.io/appveyor-swagger/redoc/#operation/getProjectArtifact) to [version 0.20171123.0](https://github.com/kevinoid/appveyor-swagger/releases/tag/v0.20171123.0).  Let me know how that works for you.
